---
title: "TFModisco"
format: html
editor: visual
---

# Import Libraries

```{r}
library(readr)
library(tidyverse)

```

# Bar Plot

```{r}

df <- grouping_1_up_modisco_results_named

# Find the top 10 seqlets
top_10_tfs <- df %>%
  group_by(motif0) %>%
  summarise(total_support = sum(num_seqlets)) %>%
  arrange(desc(total_support)) %>%
  slice_head(n = 10)

# Plot
ggplot(top_10_tfs, aes(x = reorder(motif0, total_support), y = total_support)) +
  geom_col(fill = "#b15") +
  coord_flip() + 
  theme_minimal() +
  labs(
    title = "Top 10 TFs by Seqlet Count",
    subtitle = "motif0 match",
    x = "Transcription Factor",
    y = "Total Number of Seqlets"
  ) +
  theme(axis.text.y = element_text(face = "bold"))

```
# Table across cell types

```{r}

# Select for all csv files
path_to_files <- "/Users/georgiagoddard/Desktop/Research_Project/TF_Mapping/data/TFModisco"
#path_to_files <- "/Users/georgiagoddard/Desktop/Research_Project/TF_Mapping/data/TFModisco/0_Groupings"
file_list <- list.files(path = path_to_files, 
                        pattern = "\\.csv$", 
                        full.names = TRUE)
print(file_list)

# 2. Function to extract top 10 TFs from a single file
get_top_10_tfs <- function(file_name) {
  df <- read.csv(file_name)
  
  top_tfs <- df %>%
    group_by(motif0) %>%
    summarise(total_support = sum(num_seqlets)) %>%
    arrange(desc(total_support)) %>%
    slice_head(n = 10) %>%
    pull(motif0)
  
  length(top_tfs) <- 10
  return(top_tfs)
}

# Generate dataframe of TFs
summary_table <- map_dfc(file_list, ~ {
  data_frame(!!.x := get_top_10_tfs(.x))
})

# Rename columns
colnames(summary_table) <- c("Corticotrophs", "Gonadotrophs_Gata2", "Gonadotrophs", 
                             "Gonadotrophs_SF1", "Lactotrophs", "Melanotrophs", "Somatotrophs",
                             "Stem_cells", "Thyrotrophs")

# Reduce table
summary_table <- subset(summary_table, select = -c(Gonadotrophs_Gata2, Gonadotrophs_SF1))
summary_table <- summary_table %>%
  select(Stem_cells, Gonadotrophs, Corticotrophs, 
         Melanotrophs, Lactotrophs, Somatotrophs, Thyrotrophs)

# Save table
write.csv(summary_table, "/Users/georgiagoddard/Desktop/Research_Project/TF_Mapping/data/TFModisco/top_10_TFs.csv", row.names = FALSE)


```
